# Welcome to Jekyll!
#

# Site settings
title: Joanna Lamch
description: |
Programistka, fanboy Microsoftu z iPadem w ręku, kociara. 
W branży IT od 15 lat w obrębie Microsoft Technology Stack. 
#Koder C# z doświadczeniem w wielu technologiach na różne platformy docelowe. 
#Obecnie developer w projektach mobilnych (Xamarin). 
#Zwolenniczka Defensive Coding, SOLID, uczenia poprzez mentoring i ułatwiania życia programisty z wykorzystaniem dobrodziejstw współczesnego DevOps'u.
owner: Joanna Lamch # or company name
first_published: 2018 # if migrating another site, the year of your first publish
email: jlamchl@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/jlamch
  github: https://github.com/jlamch
  linkedin-square: https://linkedin.com/in/joannalamch
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
